language: java
services:
    - mysql
before_install:
    - sudo mysql -e 'CREATE DATABASE showmastertest;'
    - sudo mysql -e 'select database();'
    - sudo mysql -e CREATE USER 'userShowMaster'@'%' IDENTIFIED BY 'the_password';
    - sudo mysql -e grant all privileges on showmastertest to 'userShowMaster';
    - sudo mysql -e FLUSH PRIVILEGES;
install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
